spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/ordering?userUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
  redis:
    host: 101.201.181.147
    port: 6379
#    password :

#  freemarker:
#        templateLoaderPath: classpath:/templates/
server:
  servlet:
    context-path: /sell
#wechat:
#  openAppId: wxd3e5e714d21715d5
#  openAppSecret: 8575daccab7c8c11dcaf623e8ee245e9
projecturl:
  #  wechatMpAuthorize: http://sell.natapp4.cc
  #  wechatOpenAuthorize: http://sell.natapp4.cc
  sell: http://localhost:8080
logging:
  level:
    com.shuai.ordering.pojo.mapper: trace
mabatis:
  mapper-locations: classpath:mapper/*.xml